# http://www.appveyor.com/docs/appveyor-yml

# init
clone_depth: 20
init:
- git config --global core.autocrlf false

environment:
  matrix:
  - nodejs_version: 0.10
  - nodejs_version: 0.12
  - nodejs_version: 1
  - nodejs_version: 2
  - nodejs_version: 3
  - nodejs_version: 4
  - nodejs_version: 5

# install
install:
- ps: Install-Product node $env:nodejs_version
- node --version
- npm --version
- npm install
- where npm

# build
build: off

# test
test_script:
- npm test

# deploy
deploy: off

# notify
notifications:
- provider: Email
  to:
  - o.gata.ken@gmail.com
  on_build_status_changed: true
